/**:
  ros__parameters:
    # Preprocessing
    max_range: 7.0
    min_range: 0.0
    # Mapping parameters
    voxel_size: 0.075       #
    max_points_per_voxel: 1 #
    min_consecutive_observations: 4 #

    # Correspondence threshold parameters
    use_adaptive_threshold: true #ma minimalny vplyv 
    fixed_threshold: 1.0 # Ignored if use_adaptive_threshold=true

    # Registration Parameters - ci viac kiss alebo kolesa
    max_num_iterations: 10
    convergence_criterion: 0.001
    max_num_threads: 1
    use_adaptive_odometry_regularization: false  #
    # use_adaptive_odometry_regularization: true  # KOBUKI
    fixed_regularization: 0.0001 # Ignored if use_adaptive_odometry_regularization=true

    # Motion Compensation
    deskew: false

    # Covariance diagonal values
    orientation_covariance: 0.1
    position_covariance: 0.1
